=== Puppo/xe-website/schemas/partners.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "image": {
        "type": "string"
      },
      "imageHeight": {
        "type": "integer",
        "exclusiveMinimum": 0,
        "maximum": 9007199254740991
      },
      "imageWidth": {
        "type": "integer",
        "exclusiveMinimum": 0,
        "maximum": 9007199254740991
      },
      "kind": {
        "type": "string",
        "enum": [
          "sponsor",
          "supporter"
        ]
      },
      "name": {
        "type": "string"
      },
      "order": {
        "type": "integer",
        "exclusiveMinimum": 0,
        "maximum": 9007199254740991
      },
      "published": {
        "default": true,
        "type": "boolean"
      },
      "url": {
        "type": "string",
        "format": "uri"
      },
      "id": {
        "type": "string",
        "minLength": 1
      }
    },
    "required": [
      "kind",
      "name",
      "url",
      "id"
    ]
  },
  "$id": "https://www.xedotnet.org/schemas/partners.schema.json",
  "title": "XeDotNet partners"
}

=== Puppo/xe-website/src/data/partners.json
[
  {
    "id": "sessionize",
    "name": "Sessionize",
    "url": "https://sessionize.com/",
    "image": "/media/1184-sessionize-logo.png",
    "imageWidth": 200,
    "imageHeight": 99,
    "order": 1,
    "kind": "sponsor"
  },
  {
    "id": "eventitech",
    "name": "Eventitech",
    "url": "https://eventitech.it/",
    "image": "/media/1223-logo-eventitech-200.png",
    "imageWidth": 200,
    "imageHeight": 47,
    "order": 2,
    "kind": "sponsor"
  },
  {
    "id": "jetbrains",
    "name": "JetBrains",
    "url": "https://www.jetbrains.com/",
    "kind": "supporter",
    "published": false
  },
  {
    "id": "telerik",
    "name": "Telerik",
    "url": "https://www.telerik.com/",
    "kind": "supporter",
    "published": false
  },
  {
    "id": "redgate",
    "name": "Redgate",
    "url": "https://www.red-gate.com/",
    "kind": "supporter",
    "published": false
  },
  {
    "id": "hunext",
    "name": "Hunext",
    "url": "https://www.hunext.com/",
    "image": "/media/1020-hunext-hrsolutions-200x100.png",
    "imageWidth": 200,
    "imageHeight": 100,
    "order": 3,
    "kind": "supporter"
  },
  {
    "id": "yalp",
    "name": "Yalp",
    "url": "https://www.yalp.me/",
    "image": "/media/1117-yalp-200x100.png",
    "imageWidth": 200,
    "imageHeight": 100,
    "order": 4,
    "kind": "supporter"
  }
]
